spring:
  application:
    name: cart-service

  data:
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000

  mongodb:
    host: localhost
    port: 27017
    database: cart-service

products:
  client:
    API: https://fakestoreapi.com/